### ISSUE TITLE
[bug] gradle 构建失败

### ISSUE THREAD

**Issue by VVVVictorJ** [TYUpya/UpyaSelectFileOrFolder#1]
![image](https://user-images.githubusercontent.com/38826071/75621633-bcad7c00-5bd1-11ea-9dfd-82ce6385e746.png)

**Comment by VVVVictorJ** [comment]
demo没有问题，就是不知道这个哪里不对了

**Comment by VVVVictorJ** [comment]
![image](https://user-images.githubusercontent.com/38826071/75621758-912b9100-5bd3-11ea-973f-8b5b51974adb.png)
clean project zhi之后是上图

**Comment by VVVVictorJ** [comment]
maven填错位置了，监介

**Comment by TYUpya** [comment]
感谢您的使用！没问题就好。欢迎提出意见和建议！谢谢！

**Comment by VVVVictorJ** [comment]
@TYUpya 
还要在gradle那里加compileOptions，不然会报错
```bash
   compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

**Comment by TYUpya** [comment]
好的，非常感谢！我会优化Readme，使库更容易使用。
