### ISSUE TITLE
readme 完善

### ISSUE THREAD

**Issue by VVVVictorJ** [TYUpya/UpyaSelectFileOrFolder#2]
添加权限不一定管用，demo的直接用可以，有时候读取不到，要手动在应用管理开

**Comment by TYUpya** [comment]
是不一定有用，所以你得在合适的地方调用申请权限 android.permission.READ_EXTERNAL_STORAGE。

**Comment by VVVVictorJ** [comment]
@TYUpya 好的，谢谢。
